version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Assuming your frontend runs on port 3000

  backend:
    build: ./backend
    ports:
      - "5000:5000" # Assuming your backend runs on port 5000
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - "3306:3306" # Expose MySQL port for external access
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
